name: th_rosenheim
description: Shows the Timetable as well as Cantine information for the Rosenheim Technical University of Applied Sciences
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Logging
  logger: ^0.9.1

  # Network / API Requests
  dio: ^3.0.9
  dio_http_cache: ^0.2.7

  # State management
  bloc: ^4.0.0
  flutter_bloc: ^4.0.1

  # Data models
  equatable: ^1.1.1
  json_annotation: ^3.0.1

  # Html parsing
  html: ^0.14.0+3

  # Widgets
  bubble_bottom_bar: ^1.2.0
  cached_network_image: ^2.2.0+1
  md2_tab_indicator: ^1.0.2
  flutter_staggered_grid_view: ^0.3.0
  auto_size_text: ^2.1.0
  photo_view: ^0.9.0

  # Internationalisation
  intl: ^0.16.1

  # Utilities
  url_launcher: ^5.4.11
  path_provider: ^1.5.1
  shared_preferences: ^0.5.7+3

  # Icons
  material_design_icons_flutter: ^4.0.5345

  # Code Style
  effective_dart: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Json generation
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/lageplan.png
    - assets/sleep.png
    - assets/additives/
    - assets/locale/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
